In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [22]:
train = pd.read_csv('/content/drive/MyDrive/data/hand_movement_dacon/train.csv')
test = pd.read_csv('/content/drive/MyDrive/data/hand_movement_dacon/test.csv')
submission = pd.read_csv('/content/drive/MyDrive/data/hand_movement_dacon/sample_submission.csv')

In [23]:
train

id   sensor_1   sensor_2   sensor_3   sensor_4   sensor_5   sensor_6  \
0        1  -6.149463  -0.929714   9.058368  -7.017854  -2.958471   0.179233   
1        2  -2.238836  -1.003511   5.098079 -10.880357  -0.804562  -2.992123   
2        3  19.087934  -2.092514   0.946750 -21.831788   9.119235  17.853587   
3        4  -2.211629  -1.930904  21.888406  -3.067560  -0.240634   2.985056   
4        5   3.953852   2.964892 -36.044802   0.899838  26.930210  11.004409   
...    ...        ...        ...        ...        ...        ...        ...   
2330  2331  -3.971043  39.913391  16.034626 -19.067697   8.061361 -70.916786   
2331  2332  -3.011710  -4.060355  -1.046067   4.178137  -2.003243  -2.895017   
2332  2333  -9.001824   5.985711  -8.146347 -10.902201   5.102105   8.133692   
2333  2334  -3.987992   3.011460 -11.949323  -3.810885  16.880234  -5.150117   
2334  2335  -1.838225  -7.023497 -45.877365  20.026927   4.058551   8.062100   

       sensor_7   sensor_8   sensor_9  ...  sensor_24  sensor_25  sensor_26  \
0     -0.956591  -0.972401   5.956213  ...  -7.026436  -6.006282  -6.005836   
1     26.972724  -8.900861  -5.968298  ...  -1.996714  -7.933806  -3.136773   
2    -21.069954 -15.933212  -9.016039  ...  -6.889685  54.052330  -6.109238   
3    -29.073369   0.200774  -1.043742  ...  -2.126170  -1.035526   2.178769   
4    -21.962423 -11.950189 -20.933785  ...  -2.051761  10.917567   1.905335   
...         ...        ...        ...  ...        ...        ...        ...   
2330 -39.937026  12.834223 -21.937973  ...   3.086417  -4.954858 -11.106802   
2331  -2.766757 -29.099123  -4.208953  ...   6.871938  -0.134367  -0.867018   
2332  32.877614  -3.017438  -3.174442  ...  -7.952857   2.049467  -5.825790   
2333   9.182801   4.960190 -21.002525  ...   3.080276   2.054739  -1.052350   
2334  19.083782 -21.881795  -9.106341  ...  31.130021   5.121935  -1.003704   

      sensor_27  sensor_28  sensor_29  sensor_30  sensor_31  sensor_32  target  
0      7.043084  21.884650  -3.064152  -5.247552  -6.026107 -11.990822       1  
1      8.774211  10.944759   9.858186  -0.969241  -3.935553 -15.892421       1  
2     12.154595   6.095989 -40.195088  -3.958124  -8.079537  -5.160090       0  
3     10.032723  -1.010897  -3.912848  -2.980338 -12.983597  -3.001077       1  
4    -13.004707  17.169552   2.105194   3.967986  11.861657 -27.088846       2  
...         ...        ...        ...        ...        ...        ...     ...  
2330 -37.863399  31.069292  -4.097017 -13.095192  -5.150284   8.016265       3  
2331  23.892336 -11.977934   1.984203   0.891666  28.822082  -0.878670       3  
2332 -37.989569  15.014132   1.160272 -11.135889  -7.035763  -0.930067       3  
2333  -6.019488  -7.075333  -5.826058  -3.989168  14.916905 -12.093426       1  
2334 -58.953961 -22.095226  -0.898581   1.164833 -21.977991 -13.060285       2  

[2335 rows x 34 columns]

In [24]:
X_train = train.drop(['id', 'target'], axis = 1)
X_test = test.drop('id', axis=1)

mins = X_train.min()
maxs = X_train.max()
X_train = (X_train - mins) / (maxs - mins)
X_test = (X_test - mins) / (maxs - mins)

In [25]:
X_train

sensor_1  sensor_2  sensor_3  sensor_4  sensor_5  sensor_6  sensor_7  \
0     0.541473  0.606731  0.526447  0.490227  0.497738  0.671732  0.464596   
1     0.565373  0.606021  0.510563  0.472168  0.509495  0.641768  0.588175   
2     0.695714  0.595535  0.493912  0.420966  0.563662  0.838724  0.375600   
3     0.565540  0.597091  0.577908  0.508696  0.512573  0.698242  0.340187   
4     0.603221  0.644232  0.345542  0.527245  0.660879  0.774011  0.371651   
...        ...       ...       ...       ...       ...       ...       ...   
2330  0.554787  1.000000  0.554429  0.433889  0.557887  0.000000  0.292118   
2331  0.560650  0.576587  0.485919  0.542573  0.502952  0.642686  0.456586   
2332  0.524041  0.673318  0.457441  0.472066  0.541735  0.746888  0.614303   
2333  0.554683  0.644680  0.442187  0.505221  0.606023  0.621379  0.509460   
2334  0.567822  0.548056  0.306105  0.616672  0.536039  0.746211  0.553269   

      sensor_8  sensor_9  sensor_10  ...  sensor_23  sensor_24  sensor_25  \
0     0.447091  0.561398   0.548431  ...   0.404892   0.473689   0.592187   
1     0.412336  0.484649   0.462025  ...   0.502381   0.493417   0.579928   
2     0.381509  0.465033   0.441859  ...   0.456094   0.474226   0.974169   
3     0.452233  0.516345   0.526889  ...   0.498393   0.492909   0.623802   
4     0.398969  0.388327   0.462653  ...   0.404961   0.493201   0.699825   
...        ...       ...        ...  ...        ...        ...        ...   
2330  0.507612  0.381864   0.662126  ...   0.623888   0.513354   0.598874   
2331  0.323796  0.495972   0.454299  ...   0.576881   0.528202   0.629533   
2332  0.438126  0.502631   0.444495  ...   0.702111   0.470056   0.643423   
2333  0.473096  0.387885   0.484965  ...   0.405162   0.513330   0.643457   
2334  0.355433  0.464452   0.493654  ...   0.637609   0.623347   0.662964   

      sensor_26  sensor_27  sensor_28  sensor_29  sensor_30  sensor_31  \
0      0.551880   0.492702   0.588748   0.557137   0.625632   0.465740   
1      0.571626   0.500264   0.538340   0.657252   0.664560   0.474202   
2      0.551168   0.515030   0.515998   0.269470   0.637364   0.457429   
3      0.608209   0.505761   0.483252   0.550562   0.646261   0.437580   
4      0.606327   0.405131   0.567022   0.597186   0.709483   0.538139   
...         ...        ...        ...        ...        ...        ...   
2330   0.516773   0.296545   0.631068   0.549135   0.554226   0.469285   
2331   0.587247   0.566302   0.432719   0.596249   0.681492   0.606785   
2332   0.553119   0.295994   0.557090   0.589866   0.572054   0.461654   
2333   0.585972   0.435643   0.455309   0.535740   0.637082   0.550505   
2334   0.586306   0.204418   0.386101   0.573915   0.683978   0.401176   

      sensor_32  
0      0.488933  
1      0.471883  
2      0.518783  
3      0.528218  
4      0.422955  
...         ...  
2330   0.576363  
2331   0.537492  
2332   0.537268  
2333   0.488484  
2334   0.484259  

[2335 rows x 32 columns]

In [26]:
X_train_re = np.array(X_train).reshape(-1, 1,8,4)

In [27]:
X_train_re

array([[[[0.54147306, 0.60673137, 0.52644741, 0.4902271 ],
         [0.49773803, 0.6717322 , 0.46459578, 0.44709051],
         [0.56139802, 0.54843076, 0.57995866, 0.48733382],
         ...,
         [0.50665409, 0.64498686, 0.40489171, 0.47368931],
         [0.59218715, 0.55187984, 0.49270206, 0.58874753],
         [0.55713742, 0.62563154, 0.46574017, 0.48893287]]],


       [[[0.56537327, 0.60602079, 0.51056301, 0.47216842],
         [0.50949467, 0.64176847, 0.58817528, 0.41233576],
         [0.4846488 , 0.46202484, 0.48917722, 0.48247749],
         ...,
         [0.51204895, 0.58329708, 0.5023806 , 0.49341691],
         [0.57992779, 0.57162578, 0.50026385, 0.53833977],
         [0.65725166, 0.66455976, 0.47420151, 0.47188309]]],


       [[[0.69571409, 0.59553503, 0.49391236, 0.4209663 ],
         [0.56366155, 0.83872373, 0.37559972, 0.38150915],
         [0.46503275, 0.44185945, 0.38150058, 0.46298375],
         ...,
         [0.45454767, 0.69467941, 0.45609415, 0.47422568],
      

In [28]:
X_test_re = np.array(X_test).reshape(-1,1,8,4)

In [29]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

import random
random.seed(42)
torch.manual_seed(42)

In [30]:
X_train_re_tensor = torch.tensor(X_train_re, dtype= torch.float32)

In [31]:
X_train_re_tensor

tensor([[[[0.5415, 0.6067, 0.5264, 0.4902],
          [0.4977, 0.6717, 0.4646, 0.4471],
          [0.5614, 0.5484, 0.5800, 0.4873],
          ...,
          [0.5067, 0.6450, 0.4049, 0.4737],
          [0.5922, 0.5519, 0.4927, 0.5887],
          [0.5571, 0.6256, 0.4657, 0.4889]]],


        [[[0.5654, 0.6060, 0.5106, 0.4722],
          [0.5095, 0.6418, 0.5882, 0.4123],
          [0.4846, 0.4620, 0.4892, 0.4825],
          ...,
          [0.5120, 0.5833, 0.5024, 0.4934],
          [0.5799, 0.5716, 0.5003, 0.5383],
          [0.6573, 0.6646, 0.4742, 0.4719]]],


        [[[0.6957, 0.5955, 0.4939, 0.4210],
          [0.5637, 0.8387, 0.3756, 0.3815],
          [0.4650, 0.4419, 0.3815, 0.4630],
          ...,
          [0.4545, 0.6947, 0.4561, 0.4742],
          [0.9742, 0.5512, 0.5150, 0.5160],
          [0.2695, 0.6374, 0.4574, 0.5188]]],


        ...,


        [[[0.5240, 0.6733, 0.4574, 0.4721],
          [0.5417, 0.7469, 0.6143, 0.4381],
          [0.5026, 0.4445, 0.5510, 0.5269],
    

In [32]:
X_test_re_tensor = torch.tensor(X_test_re, dtype = torch.float32)

In [33]:
y_train_tensor = torch.tensor(train['target'].to_numpy(), dtype = torch.int64)

In [34]:
train_dataset = TensorDataset(X_train_re_tensor, y_train_tensor)

In [35]:
train_dataloader = DataLoader(train_dataset, batch_size = 16, shuffle = True)
for batch_idx, samples in enumerate(train_dataloader):
    if batch_idx > 0:
        break
    print(samples[0].shape)
    print(samples[1])

torch.Size([16, 1, 8, 4])
tensor([1, 3, 1, 1, 1, 2, 1, 0, 3, 0, 3, 0, 3, 2, 2, 0])


In [50]:
#https://justkode.kr/deep-learning/pytorch-cnn 
#위에 참고

class FlattenLayer(nn.Module):
  def forward(self, x):
    sizes = x.size()
    return x.view(sizes[0],-1)

class CNN(nn.Module):
  def __init__(self):
    super().__init__()
    self.layer1 = nn.Sequential(
        nn.Conv2d(in_channels=1, out_channels = 16, kernel_size =2, stride = 1),
        nn.BatchNorm2d(num_features=16),
        nn.ReLU(),
        nn.Conv2d(in_channels = 16, out_channels = 32, kernel_size = 2, stride =1),
        nn.BatchNorm2d(32),
        nn.ReLU()
    )
    
    self.fc = nn.Linear(in_features= 32 * 6 * 2, out_features=32 ) 
    #처음 dense를 해줄때 나왔던 out채널의 수 그대로 해줘야됨.
    #in_features 헷갈리면 forward에 out.shape 쳐서 확인.
    self.fc2 = nn.Linear(in_features = 32, out_features = 16)
    self.fc3 = nn.Linear(16,4)


  def forward(self, x):
    out = self.layer1(x)
    out = out.view(-1, 32 * 6 * 2)
    out = self.fc(out)
    out = self.fc2(out)
    out = self.fc3(out)
    return out

In [51]:
model = CNN()
print(model)

CNN(
  (layer1): Sequential(
    (0): Conv2d(1, 16, kernel_size=(2, 2), stride=(1, 1))
    (1): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
    (3): Conv2d(16, 32, kernel_size=(2, 2), stride=(1, 1))
    (4): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): ReLU()
  )
  (fc): Linear(in_features=384, out_features=32, bias=True)
  (fc2): Linear(in_features=32, out_features=16, bias=True)
  (fc3): Linear(in_features=16, out_features=4, bias=True)
)


In [52]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.005)

for epoch in range(100):
    
    running_loss = 0.0
    accuracy = 0
    for i, data in enumerate(train_dataloader, 0):
        inputs, labels = data

        optimizer.zero_grad() # 매개변수를 0으로 만듭니다. 매 학습시 초기화해줘야합니다.
        outputs = model(inputs) # 입력값을 넣어 순전파를 진행시킵니다.
        loss = criterion(outputs, labels) # 모델 출력값와 실제값을 손실함수에 대입합니다.
        loss.backward() # 손실함수에서 역전파 수행합니다.
        optimizer.step() # 옵티마이저를 사용해 매개변수를 최적화합니다.

        running_loss += loss.item()

        _, predictions = torch.max(outputs, 1)

        for label, prediction in zip(labels, predictions):
            if label == prediction:
                accuracy = accuracy + 1

    
    if epoch%10 == 0:
      print(f'{epoch + 1} 에포크 loss: {running_loss / i:.3f}')
      print(f'{epoch + 1} 에포크 정확도: {accuracy / (i * 16):.3f}')

1 에포크 loss: 0.831
1 에포크 정확도: 0.663
11 에포크 loss: 0.308
11 에포크 정확도: 0.890
21 에포크 loss: 0.203
21 에포크 정확도: 0.925
31 에포크 loss: 0.163
31 에포크 정확도: 0.944
41 에포크 loss: 0.096
41 에포크 정확도: 0.967
51 에포크 loss: 0.121
51 에포크 정확도: 0.957
61 에포크 loss: 0.138
61 에포크 정확도: 0.961
71 에포크 loss: 0.088
71 에포크 정확도: 0.976
81 에포크 loss: 0.072
81 에포크 정확도: 0.982
91 에포크 loss: 0.045
91 에포크 정확도: 0.992


In [53]:
model.eval()

with torch.no_grad():
  outputs = model(X_test_re_tensor)
  _, pred = torch.max(outputs, 1)

pred

tensor([0, 0, 2,  ..., 0, 0, 3])

In [54]:
submission['target'] = pred.numpy()
submission['target'].value_counts()

2    2420
3    2348
0    2292
1    2283
Name: target, dtype: int64

In [55]:
submission.to_csv('dacon_hands_CNN3.csv',index=False)